version: '3'

services:
  web:
    build: .
    image: web-environment
    restart: always
    container_name: apache_nodejs
    ports: 
      - "7700:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/