name: Lint

on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: eslint install
      run: npm install eslint --save-dev
    - name: babel parser install
      run: npm install babel-eslint --save-dev
    - name: babel plugin import assertions install
      run: npm install --save-dev @babel/plugin-syntax-import-assertions
    - name: run eslint
      run: node_modules/.bin/eslint .

