on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: eslint install
      run: npm install -g eslint
    - name: run eslint
      run: eslint /home/runner/work/MathieuBonhommeau_6_07122021/MathieuBonhommeau_6_07122021/public
